name: SSH Server Deploy
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build-staticsite
        run: |
         sudo apt-get install --yes nodejs
         sudo apt-get install --yes build-essential
         npm run build
        # --   
      - name: SFTP Deploy
        # You may pin to the exact commit or the version.
        # uses: wlixcc/SFTP-Deploy-Action@fe288f8e0f466f9567fb3e54434b41800cc7b880
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          # username
          username: root
          # your sftp server
          server: ${{ secrets.DO_SVR_IP }}
          # your sftp server port, default to 22
          port: 22
          # you can copy private_key from your *.pem file, keep format
          ssh_private_key: ${{ secrets.SSH_KEY_DO_SVR_1 }}
          # will put all file under this path
          local_path: ./*
          # files will copy to under remote_path
          remote_path: /root/static/
          # sftp args
