name: SSH Server Deploy
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v3
        with:
          host: ${{ secrets.DO_SVR_IP }}
          port: 22
          username: root
          key: ${{ secrets.SSH_KEY_DO_SVR_1 }}
          scp_source: ./*
          scp_target: ~/
          before_script: |
            df -h
          after_script: |
            whoami
