name: SSH Server Deploy
on:
  workflow_dispatch:
    branches: main
jobs:
  build:
    name: Build  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build-staticsite
        run: |
         ls -lha
         pwd 
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          # username
          username: root
          # your sftp server
          server: ${{ secrets.DO_SVR_IP }}
          # your sftp server port, default to 22
          port: 22
          # you can copy private_key from your *.pem file, keep format
          ssh_private_key: ${{ secrets.SSH_KEY_DO_SVR_1 }}
          # will put all file under this path
          local_path: ./build/*
          # files will copy to under remote_path
          remote_path: /root/static/
          # sftp args
